apiVersion: v1
kind: Namespace
metadata:
  name: clusters-sub
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops-siteconfig
  project: default
  source:
    path: clusters/vbmc-test-cluster01.rtp.raleigh.ibm.com/ztp/siteconfig
    repoURL: https://github.com/maheshd2/telco-gitops-1.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
