apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - argocd-openshift-gitops.yaml
  - gitops-cluster-rolebinding.yaml
  - app-project.yaml
  - namespace.yaml

  - hook-cluster-sub-role.yaml      # sitecoonfigs.ran.openshift.io
  - hook-cluster-sub-binding.yaml   # sitecoonfigs.ran.openshift.io

  - site-config-crd.yaml