apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-ocp-48-cluster-vbmc.vran.ibm.com-gitops
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
#    namespace: test-sno-siteconfig
  project: default
  source:
    path: clusters/new-ocp-48-cluster-vbmc.vran.ibm.com/ztp/gitops
    repoURL: https://github.com/maheshd2/telco-gitops-1
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
